apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api

  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: my-go-app
          image: my-go-app:latest
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
