name: Deploy to AWS EC2

on:
  push:
    branches: [master]
    paths:
      - '**.go'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - 'config.ini'
      - '.github/workflows/docker-build.yml'
      - '.github/workflows/deploy.yml'
jobs:
  deploy:
    runs-on:
      ubuntu-latest

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull serhiihulko/my-go-app:latest
            docker stop my-go-app || true
            docker rm my-go-app || true
            docker run -d --name my-go-app -p 80:80 serhiihulko/my-go-app:latest
