name: Deploy to AWS EC2

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull serhiihulko/my-go-app:latest
            docker stop my-go-app || true
            docker rm my-go-app || true
            docker run -d --name my-go-app -p 80:80 serhiihulko/my-go-app:latest
